apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qm5jduh5x-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/qm5jduh5x-java-quarkus-gitops